#!/bin/bash

ROOT="$(cd "$(dirname "$0")"; pwd)"

set -e
set -x

cd "$ROOT"
ln -shf "$ROOT/.vimrc" ~/.vimrc
ln -shf "$ROOT/.bash_profile" ~/.bash_profile
ln -shf "$ROOT/.bashrc" ~/.bashrc
sudo ln -shf "$ROOT/.vim/" ~

