#!/bin/bash

ROOT="$(cd "$(dirname "$0")"; pwd)"

set -e
set -x

cd "$ROOT"
ln -sf "$ROOT/.vimrc" ~/.vimrc
ln -sf "$ROOT/.bash_profile" ~/.bash_profile
ln -sf "$ROOT/.bashrc" ~/.bashrc
sudo ln -sf "$ROOT/.vim/" ~

